/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.ControlMovieInfo;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import model.Movie;
import model.User;

/**
 *
 * @author ekpri
 */
public class MovieInfoPanel extends javax.swing.JFrame {
    private Movie movie;
    private User user;
    private ControlMovieInfo control;
    private Connection conn;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MovieInfoPanel.class.getName());

    /**
     * Creates new form VideoInfoPanel
     */
    public MovieInfoPanel(Movie movie, User user, Connection conn) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        this.movie = movie;
        this.user = user;
        this.conn = conn;
        this.control = new ControlMovieInfo(conn);
        
        loadInfo();
        
        //Set Icon Image
        setScaledIcon(lblFavIcon, "/resources/star.png");
        setScaledIcon(lblThumb, "/resources/default_thumbnail.png");
        lblFavIcon.setEnabled(false);
        
        //Set Icons as button
        asButton(lblFavIcon, () -> btnAddListActionPerformed());
    }
    
    private void asButton(JLabel label, Runnable action) {
        label.setCursor(new Cursor(Cursor.HAND_CURSOR));
        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                action.run();
            }
        });
    }
    
    private void loadInfo() {
        lblTitle.setText(movie.getTitle());
        lblDirector.setText("Director: " + movie.getDirector());
        lblGenre.setText("Genre: " + movie.getGenre());
        lblDescrp.setText(movie.getDescription());
        lblTime.setText("Time: " + control.formatDuration(movie.getDuration()));
        
        try {
            boolean isFavorite = control.checkIfFavorite(user, movie);
            lblFavIcon.setEnabled(isFavorite);
        } catch (SQLException e) {
            lblFavIcon.setEnabled(false);
            System.err.println("Erro ao verificar favorito: " + e.getMessage());
        }
        
        updateLikeButton();
    }
    
    private void setScaledIcon(JLabel label, String resourcePath) {
        try {
            ImageIcon originalIcon = 
                new ImageIcon(getClass().getResource(resourcePath));

            int width = label.getWidth();
            int height = label.getHeight();

            Image scaledImg = originalIcon.getImage().getScaledInstance(
                    width, height, Image.SCALE_SMOOTH
            );
            label.setIcon(new ImageIcon(scaledImg));
        } catch (Exception e) {
            System.err.println("Erro ao cargegar ícone: " + resourcePath);
        }
    }

    private void updateLikeButton() {
        try {
            boolean liked = control.checkIfLiked(user, movie);
            btnLike.setText(liked ? "Dislike" : "Like");
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e, "Erro", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnAddListActionPerformed() {
        try {
            boolean isNowFavorite = control.toggleFavorite(user, movie);
            
            lblFavIcon.setEnabled(isNowFavorite);

            String msg = isNowFavorite ? "Filme adicionado aos favoritos!" 
                    : "Filme removido dos favoritos!";
            JOptionPane.showMessageDialog(this, msg);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Erro ao processar favoritos: " + e.getMessage(), 
                "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblThumb = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblDirector = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        lblDescrp = new javax.swing.JLabel();
        btnLike = new javax.swing.JButton();
        lblFavIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("TITLE");

        lblTime.setText("TIME");

        lblDirector.setText("DIRECTOR");

        lblGenre.setText("GENRE");
        lblGenre.setBorder(javax.swing.BorderFactory.createTitledBorder("GENRE"));

        lblDescrp.setBorder(javax.swing.BorderFactory.createTitledBorder("DESCRIPTION"));

        btnLike.addActionListener(this::btnLikeActionPerformed);

        lblFavIcon.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDescrp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(144, 144, 144)))
                            .addComponent(lblThumb, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFavIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLike, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblThumb, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblGenre))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFavIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnLike, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTime, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addGap(45, 45, 45)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescrp, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLikeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLikeActionPerformed
        try {
            control.toggleLike(user, movie);
            updateLikeButton();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao processar like: " + e.getMessage());
        }
    }//GEN-LAST:event_btnLikeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
//            logger.log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new MovieInfoPanel().setVisible(true));
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLike;
    private javax.swing.JLabel lblDescrp;
    private javax.swing.JLabel lblDirector;
    private javax.swing.JLabel lblFavIcon;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblThumb;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
